export default [
  {
    'name': '流程属性',
    'children': [
      {
        'CP_ID': '1000204101',
        'CP_CODE': 'code',
        'CP_NAME': 'CODE',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '流程属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': null,
        'orderno': 1,
        'value': null
      },
      {
        'CP_ID': '1000204101',
        'CP_CODE': 'id',
        'CP_NAME': '活动ID',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '流程属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': null,
        'orderno': 1,
        'value': null,
        'visiable': 0
      },
      {
        'CP_ID': '1000204102',
        'CP_CODE': 'text',
        'CP_NAME': '任务名称',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '流程属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': '添加条件',
        'orderno': 2,
        'value': null,
        'visiable': 0
      },
      {
        'CP_ID': '1000204103',
        'CP_CODE': 'icon',
        'CP_NAME': '图标',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '流程属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': null,
        'orderno': 3,
        'value': null
      }]
  },
  {
    'name': '图形属性',
    'children': [
      {
        'CP_ID': '1000204901',
        'CP_CODE': 'width',
        'CP_NAME': '宽度',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'integer',
        'DEFAULVALUE': '80',
        'orderno': 1,
        'value': null,
        'READONLY': 0
      },
      {
        'CP_ID': '1000204902',
        'CP_CODE': 'height',
        'CP_NAME': '高度',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'integer',
        'DEFAULVALUE': '40',
        'orderno': 2,
        'value': null,
        'READONLY': 0
      },
      {
        'CP_ID': '1000204903',
        'CP_CODE': 'borderWeight',
        'CP_NAME': '边框宽度',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'float',
        'DEFAULVALUE': '1',
        'orderno': 3,
        'value': null
      },
      {
        'CP_ID': '1000204904',
        'CP_CODE': 'borderColor',
        'CP_NAME': '边框颜色',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': '#797979',
        'orderno': 4,
        'value': null
      },
      {
        'CP_ID': '1000204905',
        'CP_CODE': 'borderRadius',
        'CP_NAME': '边框角',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': '5',
        'orderno': 5,
        'value': null
      },
      {
        'CP_ID': '1000204906',
        'CP_CODE': 'borderDash',
        'CP_NAME': '边框线',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'array-integer',
        'DEFAULVALUE': '',
        'orderno': 5,
        'value': null
      },
      {
        'CP_ID': '1000204907',
        'CP_CODE': 'selectedBorderWeight',
        'CP_NAME': '边框宽度-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'float',
        'DEFAULVALUE': '1',
        'orderno': 6,
        'value': null
      },
      {
        'CP_ID': '1000204908',
        'CP_CODE': 'selectedBorderColor',
        'CP_NAME': '边框颜色-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': '#797979',
        'orderno': 7,
        'value': null
      },
      {
        'CP_ID': '1000204909',
        'CP_CODE': 'selectedBorderRadius',
        'CP_NAME': '边框角-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'DEFAULVALUE': '5',
        'orderno': 8,
        'value': null
      },
      {
        'CP_ID': '1000204910',
        'CP_CODE': 'selectedBorderDash',
        'CP_NAME': '边框线-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'array-integer',
        'DEFAULVALUE': '',
        'orderno': 9,
        'value': null
      },
      {
        'CP_ID': '1000204911',
        'CP_CODE': 'fillColor',
        'CP_NAME': '填充色',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '#FFFFFF',
        'orderno': 10,
        'value': null
      },
      {
        'CP_ID': '1000204912',
        'CP_CODE': 'selectedFillColor',
        'CP_NAME': '填充色-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '#FFFFFF',
        'orderno': 11,
        'value': null
      },
      {
        'CP_ID': '1000204913',
        'CP_CODE': 'fontFamily',
        'CP_NAME': '字体',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': 'PingFangSC-Light',
        'orderno': 12,
        'value': null
      },
      {
        'CP_ID': '1000204914',
        'CP_CODE': 'fontColor',
        'CP_NAME': '字体-颜色',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '#187CFF',
        'orderno': 13,
        'value': null
      },
      {
        'CP_ID': '1000204915',
        'CP_CODE': 'fontSize',
        'CP_NAME': '字体-大小',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'integer',
        'DEFAULVALUE': '14',
        'orderno': 14,
        'value': null
      },
      {
        'CP_ID': '1000204916',
        'CP_CODE': 'selectedFontFamily',
        'CP_NAME': '字体-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': 'PingFangSC-Light',
        'orderno': 15,
        'value': null
      },
      {
        'CP_ID': '1000204917',
        'CP_CODE': 'selectedFontColor',
        'CP_NAME': '字体-颜色',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'colorPicker',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '#187CFF',
        'orderno': 16,
        'value': null
      },
      {
        'CP_ID': '1000204918',
        'CP_CODE': 'selectedFontSize',
        'CP_NAME': '字体大小-选中',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '图形属性',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': null,
        'CP_DATA_TYPE': 'integer',
        'DEFAULVALUE': '14',
        'orderno': 17,
        'value': null
      },
    ]
  },
  {
    'name': '事件',
    'children': [
      {
        'CP_ID': '1000204301',
        'CP_CODE': 'mouseoverlistener',
        'CP_NAME': '鼠标移入事件',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '事件',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': '',
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '',
        'orderno': 1,
        'value': null
      },
      {
        'CP_ID': '1000204302',
        'CP_CODE': 'mouseoutlistener',
        'CP_NAME': '鼠标移出事件',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '事件',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': '',
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': '',
        'orderno': 2,
        'value': null
      },
      {
        'CP_ID': '1000204303',
        'CP_CODE': 'onclicklistener',
        'CP_NAME': '鼠标点击事件',
        'CONTROL_ID': '1000204',
        'GROUPNAME': '事件',
        'CP_CONTROL_TYPE': 'text',
        'CP_DATA_SOURCE': '',
        'CP_DATA_TYPE': '',
        'DEFAULVALUE': 'window.tempfunc.quickCreateConditionActivity',
        'orderno': 3,
        'value': null,
        'visiable': 0
      }]
  }]